// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskManagement.Models;

#nullable disable

namespace RiskManagement.Migrations
{
    [DbContext(typeof(RiskManagementDbContext))]
    [Migration("20260407090000_AddIncidentTable")]
    partial class AddIncidentTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // ... The rest of the model snapshot code should be generated by EF Core tooling ...
            // If you need a full designer file, run 'dotnet ef migrations add' or 'dotnet ef database update' to regenerate.
#pragma warning restore 612, 618
        }
    }
}
